spring:
  application:
    name: chat-call
  liquibase:
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    change-log: classpath:db/changelog/db.changelog-master.yaml
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        schema: public
  r2dbc:
    url: ${R2DBC_URL}
    properties:
      schema: public
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    log-level: DEBUG
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
    initialization-mode: none
  rabbitmq:
    host: localhost # RabbitMQ host (localhost if running on the same machine)
    port: 5672 # Default RabbitMQ port
    username: guest # Default RabbitMQ username
    password: guest # Default RabbitMQ password
    virtual-host: / # Default virtual host ("/")
    listener:
      simple:
        retry:
          enabled: true # Enable retry for message consumption
          initial-interval: 1000 # Initial retry interval in milliseconds
          max-attempts: 5 # Maximum number of retry attempts
        acknowledge-mode: auto # Auto acknowledgment of messages
  sql:
    init:
      platform: postgresql
      mode: always

  data:
    redis:
      host: localhost
      port: 6379
    r2dbc:
      repositories:
        enabled: true # Enable reactive repositories

server:
  port: 8085

logging:
  level:
    io:
      r2dbc:
        postgresql:
          query: DEBUG
        client:
          sql:
            enabled: false

socket-server:
  port: 8085
  host: localhost
